### ISSUE TITLE
It is weird that a cancellationException do be catched in the stop method of LanguageServerWrapper class when multithreading

### ISSUE THREAD

**Issue by huangxc0930** [ballerina-platform/lsp4intellij#242]
**Description:**

the stack trace:
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.getServerCapabilities(LanguageServerWrapper.java:175)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.connect(LanguageServerWrapper.java:295)
	at org.wso2.lsp4intellij.IntellijLanguageClient.lambda$editorOpened$6(IntellijLanguageClient.java:249)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-01-26 15:00:10,378 [12500711]  ERROR - .impl.MessageBusConnectionImpl - null 
java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2276)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.stop(LanguageServerWrapper.java:402)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.getServerCapabilities(LanguageServerWrapper.java:191)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.connect(LanguageServerWrapper.java:295)
	at org.wso2.lsp4intellij.IntellijLanguageClient.lambda$editorOpened$6(IntellijLanguageClient.java:249)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Trias** [comment]
did you use the restart button? do you know how the call to stop() was triggered?

Looking at the code, it might be that an Exception or Timeout occured. Do you see something like this in the log? (Help->show log)
