### ISSUE TITLE
Not working with 2022.2+

### ISSUE THREAD

**Issue by Cammisuli** [ballerina-platform/lsp4intellij#273]
**Description:**
Trying to load a plugin that has this configured, fails on IDEs 2022.2+ (it will work with 2022.1 though).

**Steps to reproduce:**
* install this lsp (sorry it's with npm 🙁 ) `npm i -g nxls`
* Clone these repos
  * https://github.com/Cammisuli/lsp-mvp (jetbrains plugin)
  * https://github.com/Cammisuli/monodon (repo where lsp should work in)
* Set the plugin version to 2022.2 in the build.gradle.kts file
```
intellij {
    version.set("2022.2")
    type.set("IU") // Target IDE Platform

    plugins.set(listOf(/* Plugin Dependencies */))
}
```
* Build the plugin, and open this workspace https://github.com/Cammisuli/monodon
  * You would have to build the plugin with ` ./gradlew buildPlugin` and install the plugin located in `./build/distributions/lsp-mvp-1.1.zip`
* Open any project.json file (eg `packages/rust/project.json`)
* Errors appear

> Changing to 2022.1, things are working fine. 

**Affected Versions:**
lsp4intellij - 0.95
IntelliJ - 2022.2

**OS, DB, other environment details and versions:**
MacOS - Montery 12.5

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gayanper** [comment]
Do you have the error logs for this ?

**Comment by Cammisuli** [comment]
@gayanper here's the error that appears when first starting:
```
java.lang.NullPointerException: Cannot invoke "org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.getStatus()" because the return value of "org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.forProject(com.intellij.openapi.project.Project)" is null
	at org.wso2.lsp4intellij.statusbar.LSPServerStatusWidget$IconPresentation.lambda$getClickConsumer$0(LSPServerStatusWidget.java:150)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetWrapper$StatusBarWidgetClickListener.onClick(StatusBarWidgetWrapper.java:173)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by Cammisuli** [comment]
Sorry, I just realized that you have 2022.2 installed already, you can't run a plugin in debug mode with the same version. So you would have to build the plugin and install it, sorry about that.

**Comment by Cammisuli** [comment]
I'm going to close this, as I think there's some configuration issues on my side.

**Comment by nixel2007** [comment]
@Cammisuli according to logs you use intellij-lsp plugin (not this repo) and not lsp4intellij library (this repo)
