### ISSUE TITLE
missing field `codeActionKind`

### ISSUE THREAD

**Issue by ctron** [ballerina-platform/lsp4intellij#296]
**Description:**

Starting up a LSP using the `tower_lsp` implementation fails with:

```
2023-02-08 15:52:19,744 [   2957]   WARN - #o.w.l.c.l.w.LanguageServerWrapper - org.eclipse.lsp4j.jsonrpc.ResponseErrorException: missing field `codeActionKind`
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: missing field `codeActionKind`
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.getServerCapabilities(LanguageServerWrapper.java:233)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.connect(LanguageServerWrapper.java:343)
```

The message comes from the remote deserialization process, which expects a value for `org.eclipse.lsp4j.CodeActionLiteralSupportCapabilities#codeActionKind`.

The same works with VScode's LSP client.

It looks like the issue was already resolved in d7b728f6a38e8176de763b9fb617cca4507c85fd, but it is not released yet.

**Steps to reproduce:**

Connect to an LSP server implemented with `tower_lsp`.

**Affected Versions:**

0.95.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ctron** [comment]
I found that `0.95.1` was released, including this fix. Thanks!
