### ISSUE TITLE
Error when running STS4 Tooling

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#35]
**Description:**
This seems like the Runtime error which is lack of some range checking
```
SEVERE: Internal error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.wso2.lsp4intellij.client.DynamicRegistrationMethods.forName(DynamicRegistrationMethods.java:44)
	at org.wso2.lsp4intellij.client.LanguageClientImpl.lambda$null$1(LanguageClientImpl.java:76)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.lsp4intellij.client.LanguageClientImpl.lambda$registerCapability$2(LanguageClientImpl.java:74)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	... 5 more
```

**Comment by NipunaRanasinghe** [comment]
Will look into this :)

**Comment by rasika** [comment]
We need to check for non-existence of requested methods [here](https://github.com/ballerina-platform/lsp4intellij/blob/24c72567ab87686a885793df860ecc411ca4e95c/src/main/java/org/wso2/lsp4intellij/client/DynamicRegistrationMethods.java#L43). Let's return an `Optional<DynamicRegistrationMethod>`. WDYT?

**Comment by gayanper** [comment]
@rasika You mean the return value of the method ? But probably we will need to change the logic which tries to access the first element without trying look at the size of the list right ?

**Comment by rasika** [comment]
Yes. I meant below;

```java
public static Optional<DynamicRegistrationMethods> forName(final String name) {
    return Arrays.stream(DynamicRegistrationMethods.values()).filter(n -> n.name.equals(name)).findAny();
}
```
