### ISSUE TITLE
random error which opening a different project in the same window

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#64]
When opening a different project in same window while files are open which are attached to running LS, the following error is thrown
```
java.lang.Throwable: Can't remove document listener (org.wso2.lsp4intellij.editor.listeners.DocumentListenerImpl@39e98469). Registered listeners: [com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1@15f1662f, 0, 0, Multicaster, 0, 0, 0, 0, 1, 8, 1, 0, 0, [], com.intellij.openapi.editor.impl.view.LogicalPositionCache@79ff901f, com.intellij.openapi.editor.impl.view.TextLayoutCache@781af5d2, com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(com.intellij.lexer.JavaHighlightingLexer): 'package testing;

import org.springframework.beans.factory.annotation.Autowired;

import javax.naming.Context;

public class Application {
    @Autowired
    Context context;
}
', 
use soft wraps: false, tab width: 4, additional columns: false, update in progress: false, bulk update in progress: false, dirty: true, deferred regions: []
appliance manager state: recalculation in progress: false; event being processed: null, available width: 2147483647, visible width: 0, dirty: true
soft wraps mapping info: Soft wraps affected by current update: []
soft wraps: [], com.intellij.openapi.editor.impl.view.EditorSizeManager@6e479ae5, com.intellij.openapi.editor.impl.CaretModelImpl@1485bc32, com.intellij.openapi.editor.impl.InlayModelImpl$1@2bad8777, com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter@5aade7cb, Multicaster, com.intellij.openapi.fileEditor.impl.text.TextEditorComponent$MyDocumentListener@2f92ea3b, com.intellij.openapi.editor.impl.ScrollingModelImpl$1@31cc21f8]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java:994)
	at org.wso2.lsp4intellij.editor.EditorEventManager.removeListeners(EditorEventManager.java:1046)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.lambda$disconnect$2(LanguageServerWrapper.java:358)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.disconnect(LanguageServerWrapper.java:356)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.disconnect(LanguageServerWrapper.java:591)
	at org.wso2.lsp4intellij.IntellijLanguageClient.lambda$editorClosed$1(IntellijLanguageClient.java:217)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nixel2007** [comment]
#20 &

**Comment by NipunaRanasinghe** [comment]
@gayanper Shall we close this in favor of #20? :)
